### ISSUE TITLE
Offsets file is empty error

### ISSUE THREAD

**Issue by stolencatkarma** [igromanru/UE-SDK-Offsets-Updater#1]
Offsets.h path: ./Offsets.h
SDK source path: SoT-SDK/SDK
Offsets file is empty

is the output. 

also is there a discord setup yet for this? might be a good idea to pool our resources.

**Comment by stolencatkarma** [comment]
Offsets.h path: ./Offsets.h
SDK source path: SoT-SDK/SDK
[ '#pragma once \n\nclass Offsets\n{\npublic:\n\t// :APlayerController:PlayerCameraManager:SoT_Engine_classes.hpp\n\tstatic constexpr int PlayerCameraManager = 0x0518;\n\n\t// :AAthenaCharacter:WieldedItemComponent:SoT_Athena_classes.hpp\n\tstatic constexpr int WieldedItemComponent = 0x820;\n\t// :AAthenaCharacter:HealthComponent:SoT_Athena_classes.hpp\n\tstatic constexpr int HealthComponent = 0x848;\n\n\t// :UWieldedItemComponent:CurrentlyWieldedItem:SoT_Athena_classes.hpp\n\tstatic constexpr int CurrentlyWieldedItem = 0x02A8;\n\n\t// :AWieldableItem:ItemName:SoT_Athena_classes.hpp\n\tstatic constexpr int WieldableItemName = 0x580; // ItemName property\n\n\t// :APlayerCameraManager:CameraCache:SoT_Engine_classes.hpp\n\tstatic constexpr int CameraCache = 0x0500;\n\t// :FCameraCacheEntry:POV:SoT_Engine_structs.hpp\n\tstatic constexpr int CameraCachePOV = CameraCache + 0x10;\n\tstatic constexpr int CameraLocation = CameraCachePOV + 0x0;\n\tstatic constexpr int CameraRotation = CameraCachePOV + 0xC;\n\tstatic constexpr int CameraFOV = CameraCachePOV + 0x18;\n\n\t// :UIslandDataAsset:IslandDataEntries:SoT_Athena_classes.hpp\n\tstatic constexpr int IslandDataEntries = 0x40;\n\tstatic constexpr int IslandDataEntriesCount  = IslandDataEntries + 0x8;\n\n\t// :UIslandDataAssetEntry:IslandName:SoT_Athena_classes.hpp\n\tstatic constexpr int IslandName = 0x0028;\n\t// :UIslandDataAssetEntry:TreasureMaps:SoT_Athena_classes.hpp\n\tstatic constexpr int TreasureMaps = 0x30;\n\n\t// :AXMarksTheSpotMap:MapTexturePath:SoT_Athena_classes.hpp\n\tstatic constexpr int MapTexturePath = 0x888;\n\t// :AXMarksTheSpotMap:Marks:SoT_Athena_classes.hpp\n\tstatic constexpr int Marks = 0x8C8;\n\tstatic constexpr int MarksCount = Marks + 0x8;\n\n#pragma region Almsonst never changing offsets\n\t// UObject\n\tstatic constexpr int Id = 0x18;\n\n\t// UWorld\n\tstatic constexpr int PersistentLevel = 0x30; // ULevel\n\tstatic constexpr int ActorsTArray = 0xA0; // Uknown offsets\n\tstatic constexpr int ActorsTArrayCount = ActorsTArray + 0x8;\n\tstatic constexpr int OwningGameInstance = 0x1C0;\n\n\t// UGameInstance\n\tstatic constexpr int LocalPlayers = 0x38;\n\n\t// UPlayer\n\tstatic constexpr int PlayerController = 0x30;\n\n\t// AActor\n\tstatic constexpr int RootComponent = 0x178;\n\n\t// APawn\n\tstatic constexpr int PlayerState = 0x4A8;\n\n\t// AController\n\tstatic constexpr int Pawn = 0x490; // LocalPlayer\n\n\t// APlayerState\n\tstatic constexpr int PlayerId = 0x4B0;\n\tstatic constexpr int PlayerName = 0x490;\n\n\t// UHealthComponent\n\tstatic constexpr int CurrentHealth = 0xDC;\n\tstatic constexpr int MaxHealth = 0xD0;\n\n\t// :USceneComponent:RelativeLocation:SoT_Engine_classes.hpp\n\tstatic constexpr int RelativeLocation = 0x01B0;\n\tstatic constexpr int RelativeRotation = RelativeLocation + 0xC;\n\tstatic constexpr int RelativeRotationYaw = RelativeRotation + 0x4;\n\n\t// :AIslandService:Marks:SoT_Athena_classes.hpp\n\tstatic constexpr int IslandDataAsset = 0x4E8;\n\n\t// FTreasureMapData\n\tstatic constexpr int TreasureLocations = 0x10;\n\tstatic constexpr int TreasureLocationsCount = TreasureLocations + 0x8;\n#pragma endregion\n};\n' ]
Offsets file is empty

looks like it's not detecting newlines properly.

**Comment by stolencatkarma** [comment]
#2 pull request should fix the issue.

**Comment by stolencatkarma** [comment]
and now we have a new bug that once you run it it makes errors in your offsets.h file.

	// :APlayerController:PlayerCameraManager:SoT_Engine_classes.hpp
	static constexpr int PlayerCameraManager = 0xerror;

	// :AAthenaCharacter:WieldedItemComponent:SoT_Athena_classes.hpp
	static constexpr int WieldedItemComponent = 0x820;
	// :AAthenaCharacter:HealthComponent:SoT_Athena_classes.hpp
	static constexpr int HealthComponent = 0x848;

**Comment by stolencatkarma** [comment]
[ '#pragma once ',
  '',
  'class Offsets',
  '{',
  'public:',
  '\t// :APlayerController:PlayerCameraManager:SoT_Engine_classes.hpp',
  '\tstatic constexpr int PlayerCameraManager = 0x0518;',
  '',

guess the /t needs to be stripped. i'll do what i can but i'm nota JS guy

**Comment by stolencatkarma** [comment]
okay so it turns out windows sees newline as /r/n whereas the file has /n/t and /n/n.

**Comment by igromanru** [comment]
Are you using linux?  
Please test the latest version.

**Comment by stolencatkarma** [comment]
not linux. will do.

**Comment by stolencatkarma** [comment]
yeah that seemed to fix it. no longer getting errors in the offsets.h file
